### PR TITLE
(#46) Only c-codes should be redirected to a pretty-url

### LINKED ISSUE #46: Only c-codes should be redirected to a pretty-url
### Issue description
*Description of the issue*
Issue #14 only requires c-codes to be redirected to pretty-urls with appended _redirect=true_ param. Currently pretty-url is also being redirected
> **ESTIMATE** 1

### Steps to reproduce the issue

1.  go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/breast-cancer?cfg=0
2. the _redirect=true_ param is  appended 

### What's the expected result?
- pretty url should not be redirected ( only c-codes) 

### What's the actual result?
- both pUrls and c-codes are redirected

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by alerosad**
Closes #46

* PrettyUrlName only appends 'redirect=true' for c-codes now
* Added integration test accordingly

### CODE REVIEW

File: src/views/CTLViewsHoC.jsx [hunk 1]
```diff
@@ -31,16 +31,20 @@ const CTLViewsHoC = (WrappedView) => {
 		const [paramType, setParamType] = useState(queryParamType.code);
 		const [queryParam, setQueryParam] = useState();
```
Comment (arcepaul) [inline src/views/CTLViewsHoC.jsx:33]: can we change your variable to `idType`?  It shouldn't start with a capital letter.

Also can we make it a const and make the setting of it a return from a function?  

There should also be an addition of a unit test(s) covering the conditions you are checking and the output value given its input.

Comment (alerosad) [reply src/views/CTLViewsHoC.jsx:33]: ok will do

**Comment by alerosad** [comment]
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-50/ @mworrest @blilianyu

File: src/views/CTLViewsHoC.jsx [hunk 2]
```diff
@@ -35,12 +35,19 @@ const CTLViewsHoC = (WrappedView) => {
...
 				? getListingInformationById
 				: getListingInformationByName;
-
 		const getListingInfo = useCustomQuery(
 			getFetchByIdOrName({ queryParam }),
 			shouldFetchListingInfo && !hasBeenRedirected
 		);
 
+		const idType = () => {
+			if (paramType !== 'code') {
```
Comment (arcepaul) [inline src/views/CTLViewsHoC.jsx:44]: no need for if/else. idType is just the result of the condition.

File: cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature [hunk 3]
```diff
@@ -5,3 +5,9 @@ Feature: As the system, I want to be able to redirect users to pretty URLs for t
 		And "pageTitle" is set to "{{disease_label}} Clinical Trials"
 		Given the user navigates to "/C4872"
 		Then the user is redirected to "/breast-cancer?redirect=true"
+
+	Scenario: Page redirects to pretty URL if pretty URL name parameter is given, without appending redirect=true
```
Comment (seyilonge-nci) [inline cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature:9]: Can you label this accordingly. Scenario described doesn't match the steps below.

File: src/views/CTLViewsHoC.jsx [hunk 4]
```diff
@@ -70,9 +77,11 @@ const CTLViewsHoC = (WrappedView) => {
 				const { prettyUrlName } = getListingInfo.payload;
 
 				setStateListingInfo(getListingInfo.payload);
-
 				// Redirect to pretty url if one exists for listing info
-				if (prettyUrlName) {
+				if (idType()) {
```
Comment (seyilonge-nci) [inline src/views/CTLViewsHoC.jsx:81]: A redirect shouldn't be happening in this case. Redirect only happens if `c-code` is used and `prettyUrlName` exists. You just have to add a negation on the "idType" `!idType()` to line 84 and remove this one like so...
```js
if (prettyUrlName && !idType()) {
  setHasBeenRedirected(true);
	const queryString = appendOrUpdateToQueryString(
	  search,
		'redirect',
		'true'
  );
	navigate(
	  `${CodeOrPurlPath({ codeOrPurl: prettyUrlName })}${queryString}`
	);
}
```

**Review by seyilonge-nci — CHANGES_REQUESTED** [review]

File: src/views/CTLViewsHoC.jsx (hunk 4 above)
Comment (seyilonge-nci) [reply src/views/CTLViewsHoC.jsx:81]: Now even wondering if the function you have above is even necessary. Why not just do
`prettyUrlName && paramType !== 'code'` and do without the function `idType`

**Review by seyilonge-nci — CHANGES_REQUESTED** [review]

File: cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature (hunk 3 above)
Comment (alerosad) [reply cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature:9]: Will do

File: src/views/CTLViewsHoC.jsx [hunk 5]
```diff
@@ -82,6 +80,9 @@ const CTLViewsHoC = (WrappedView) => {
 					navigate(
 						`${CodeOrPurlPath({ codeOrPurl: prettyUrlName })}${queryString}`
 					);
+				} else {
+					setHasBeenRedirected(false);
+					navigate(`${CodeOrPurlPath({ codeOrPurl: prettyUrlName })}${search}`);
```
Comment (sarinapadilla) [inline src/views/CTLViewsHoC.jsx:85]: I don't think we need this whole else statement and its contents. We should only be setting hasBeenRedirected and redirecting if the paramType === code, which is covered by the if(). Otherwise, we don't need to do anything.

File: src/views/CTLViewsHoC.jsx [hunk 6]
```diff
@@ -82,6 +80,9 @@ const CTLViewsHoC = (WrappedView) => {
 					navigate(
 						`${CodeOrPurlPath({ codeOrPurl: prettyUrlName })}${queryString}`
 					);
+				} else {
```
Comment (seyilonge-nci) [inline src/views/CTLViewsHoC.jsx:83]: I don't believe you need this else block. Even if you need line `84`(which I believe you can do without), you don't need line `85`. Remove this else block and test this.

File: src/views/CTLViewsHoC.jsx [hunk 7]
```diff
@@ -82,6 +80,9 @@ const CTLViewsHoC = (WrappedView) => {
 					navigate(
 						`${CodeOrPurlPath({ codeOrPurl: prettyUrlName })}${queryString}`
```
Comment (seyilonge-nci) [inline src/views/CTLViewsHoC.jsx:81]: Looking at this now, I think you might need the second parameter for `navigate` `{ replace: true }` should the user hit the back button after redirection. I missed this on the initial version.

**Review by seyilonge-nci — CHANGES_REQUESTED** [review]

File: src/views/CTLViewsHoC.jsx (hunk 5 above)
Comment (alerosad) [reply src/views/CTLViewsHoC.jsx:85]: Ok will do

File: src/views/CTLViewsHoC.jsx (hunk 7 above)
Comment (alerosad) [reply src/views/CTLViewsHoC.jsx:81]: Ok will do

**Comment by mworrest** [comment]
Tested this on the few c codes I know and it appears to work.

**Comment by sarinapadilla** [comment]
@mworrest and others, please also test pretty URL names - we want to make sure the ?redirect=true is not appended if you go straight to a valid pretty URL!

**Comment by mworrest** [comment]
Oh! Good call, if I go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-50/lung-cancer?cfg=0 or any other cancer type replacing "lung-cancer" I do not see the ?redirect=true appended.

**Review by arcepaul — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]

**Review by kate-mashkina — APPROVED** [review]
