### PR TITLE
(#103) No Trial page with CIS Banner when on-existent page number is appended to URL

### LINKED ISSUE #103: No Trial page with CIS banner and proper intro text label should be returned when a non-existent page number is appended to the url
### Issue description

The CIS banner is not appearing on the no trial page when a non-existent page number is appended to the url. For example, 
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-99/trastuzumab/treatment?cfg=1 has three pages and when we append pn=4 to it (https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-99/trastuzumab/treatment?cfg=1&pn=4), it does not display the CIS banner and does not replace the intro text label.

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-99/trastuzumab/treatment?cfg=1&pn=4
2. See that the No Trial banner is missing from the page
3. See that the intro text is missing the proper label 

### What's the expected result?
- Proper No Trial page should be displayed with CIS banner and with proper intro text labels.
- The page should navigate to noTrials route

### What's the actual result?
- The CIS banner is missing and proper intro text is not showing up.

### Additional details / screenshot
- 
image

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by alerosad**
Closes #103
*edited Invervetion.jsx and Disease.jsx redirect conditional to use payload.trials.length

### CODE REVIEW

**Comment by arcepaul** [comment]
Could you please fix your commit message? Currently it says, `($103) No Trial page with CIS Banner when on-existent page number is … ` instead of our standard format `(#103) ...`

File: src/views/Intervention/Intervention.jsx [hunk 1]
```diff
@@ -121,7 +121,11 @@ const Intervention = ({ routeParamMap, routePath, data }) => {
 
 	useEffect(() => {
 		if (!queryResponse.loading && queryResponse.payload) {
-			if (queryResponse.payload.total === 0) {
+			console.log(
```
Comment (arcepaul) [inline src/views/Intervention/Intervention.jsx:124]: remove console log

Comment (alerosad) [reply src/views/Intervention/Intervention.jsx:124]: will do

**Review by seyilonge-nci — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]
