### PR TITLE
(#60) added click event on result item

### LINKED ISSUE #60: Add click event on manual result item
### Issue description
*Description of the issue*

Manual listing page should have a click event fired on result item click

```gherkin
Scenario: Click event fires when a user clicks on result item
        Given "trialListingPageType" is set to "Manual"
        And "pageTitle" is set to "Clinical Trials for Adult Metastatic Brain Tumors"
        And "analyticsPublishedDate" is set to "02/02/2011"
        When the user navigates to "/?cfg=4"
        Then the page title is "Clinical Trials for Adult Metastatic Brain Tumors"
        When user clicks on result item 1
        Then there should be an analytics event with the following details
            | key              | value                             |
            | type             | Other                             |
            | event            | TrialListingApp:Other:ResultClick |
            | linkName         | CTSLink                           |
            | data.resultIndex | (int)1                            |
            | data.currentPage | (int)1                            |
```
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by KateMashkinaNIH**
- added tracking on the link
- added integration test
- updated unit test

Closes #60

### CODE REVIEW

File: src/views/Manual/Manual.jsx [hunk 1]
```diff
@@ -156,6 +156,7 @@ const Manual = () => {
 						<ResultsList
 							results={trialsPayload.trials}
 							resultsItemTitleLink={detailedViewPagePrettyUrlFormatter}
+							currentPage={Number(pager.page)}
```
Comment (bryanpizzillo) [inline src/views/Manual/Manual.jsx:159]: This is not really needed. You can do it as part of track.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]

File: src/views/Manual/Manual.jsx (hunk 1 above)
Comment (KateMashkinaNIH) [reply src/views/Manual/Manual.jsx]: Done!
