### PR TITLE
(#100) Fix useListingSupport

### LINKED ISSUE #100: useListingSupport does not work correctly
### Issue description
While implementing caching, it was discovered that useListingSupport does not work correctly. It only executes the very first time it is called, subsequent calls have the same exact state returned, even if the list of actions (i.e. requested API requests) have changed. 

> **ESTIMATE** TBD

### Steps to reproduce the issue
Implement a new unit test that asks for one ID action, say, C4872. Then make another request with a different id, say C1234. You will see the request for C1234 is never made.

### Related Tickets
* Issue #63

### PR DESCRIPTION
**Pull request by bryanpizzillo**
- Added parameter checking for API actions to make sure the actions
  are called with correct data.
- Added support for hashing the list of fetch actions so the app
  does not re-render itself too many times. This is for both
  useListingSupport and for CTLViewHoc.
- Added a number of tests to handle all the use cases that the
  original approach failed on.

Closes #100

### CODE REVIEW

File: src/views/__tests__/CTLViewsHoc.useListingHocInt.js [hunk 1]
```diff
@@ -0,0 +1,430 @@
...
+		});
+
+		getTrialType.mockImplementation((client, trialType) => {
+			if (trialType === 'treatment') {
+				return TRIAL_TYPE_TREATMENT;
+			}
+		});
+
+		// This should not get called.
+		const mockRedirectPath = jest.fn().mockReturnValue('');
```
Comment (seyilonge-nci) [inline src/views/__tests__/CTLViewsHoc.useListingHocInt.js:352]: Same as above

File: src/views/__tests__/CTLViewsHoc.useListingHocInt.js [hunk 2]
```diff
@@ -0,0 +1,430 @@
...
+	// TODO: Add a test for one ID to another.
+	it('should handle the request for a concept, and then handle a navigate to another concept', async () => {
+		getListingInformationByName.mockReturnValueOnce(CONCEPT_BREAST_CANCER);
+
+		getListingInformationById.mockReturnValueOnce(CONCEPT_NO_PURL);
+
+		// We use RedirectPath to figure out the correct route for
+		// a redirect. This assumes /:codeOrPurl which matches our
+		// route below.
+		const mockRedirectPath = jest.fn().mockReturnValue('/C99999');
```
[the remark this answers is not in the document]
Comment (bryanpizzillo) [reply src/views/__tests__/CTLViewsHoc.useListingHocInt.js]: Fair point, but I will meet you half-way. I will just have the mockImplementation throw and that way the code blows up cause it should not get called at all.

Right now for this PR without caching, if the redirect had occurred then the count for the API calls would be off.

File: src/views/__tests__/CTLViewsHoc.useListingHocInt.js (hunk 1 above)
Comment (bryanpizzillo) [reply src/views/__tests__/CTLViewsHoc.useListingHocInt.js]: Fair point, but I will meet you half-way. I will just have the mockImplementation throw and that way the code blows up cause it should not get called at all.

Right now for this PR without caching, if the redirect had occurred then the count for the API calls would be off.

File: src/views/__tests__/CTLViewsHoc.useListingHocInt.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (seyilonge-nci) [reply src/views/__tests__/CTLViewsHoc.useListingHocInt.js]: 👍

File: src/views/__tests__/CTLViewsHoc.useListingHocInt.js (hunk 1 above)
Comment (seyilonge-nci) [reply src/views/__tests__/CTLViewsHoc.useListingHocInt.js]: 👍

**Review by seyilonge-nci — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]
